<?php
namespace common\models;

use yii;
//use frontend\models\User;

/**
 * Task model
 *
 * @property integer $id
 * @property string $name
 * @property string $value
 */


class Config extends yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%yii_config}}';
    }

    public function fields(){
        return [
            'id',
            'name',
            'value',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['name', 'string'],
            ['name', 'unique'],
            ['value', 'string'],
        ];
    }

    public function beforeAction($action)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    
}
